-- Atualizar todas as URLs antigas para as novas URLs do Supabase Storage
UPDATE character_images SET image_url = 'https://dzrgcyhovmomyoztzmoq.supabase.co/storage/v1/object/public/character-images/Anko.png' WHERE character_name = 'Anko Mitarashi';
UPDATE character_images SET image_url = 'https://dzrgcyhovmomyoztzmoq.supabase.co/storage/v1/object/public/character-images/Asuma.png' WHERE character_name = 'Asuma Sarutobi';
UPDATE character_images SET image_url = 'https://dzrgcyhovmomyoztzmoq.supabase.co/storage/v1/object/public/character-images/Haku.png' WHERE character_name = 'Haku';
UPDATE character_images SET image_url = 'https://dzrgcyhovmomyoztzmoq.supabase.co/storage/v1/object/public/character-images/Hanabi.png' WHERE character_name = 'Hanabi Hyuuga';
UPDATE character_images SET image_url = 'https://dzrgcyhovmomyoztzmoq.supabase.co/storage/v1/object/public/character-images/Hashirama.png' WHERE character_name = 'Hashirama Senju';
UPDATE character_images SET image_url = 'https://dzrgcyhovmomyoztzmoq.supabase.co/storage/v1/object/public/character-images/Hinata SHP.png' WHERE character_name = 'Hinata Hyuuga Shippūden';
UPDATE character_images SET image_url = 'https://dzrgcyhovmomyoztzmoq.supabase.co/storage/v1/object/public/character-images/Hiruko.png' WHERE character_name = 'Hiruko';
UPDATE character_images SET image_url = 'https://dzrgcyhovmomyoztzmoq.supabase.co/storage/v1/object/public/character-images/Hiruzen.png' WHERE character_name = 'Hiruzen Sarutobi';
UPDATE character_images SET image_url = 'https://dzrgcyhovmomyoztzmoq.supabase.co/storage/v1/object/public/character-images/Ino SHP.png' WHERE character_name = 'Ino Yamanaka Shippūden';
UPDATE character_images SET image_url = 'https://dzrgcyhovmomyoztzmoq.supabase.co/storage/v1/object/public/character-images/Jiroubou.png' WHERE character_name = 'Jiroubou';
UPDATE character_images SET image_url = 'https://dzrgcyhovmomyoztzmoq.supabase.co/storage/v1/object/public/character-images/Kabuto.png' WHERE character_name = 'Kabuto Yakushi';
UPDATE character_images SET image_url = 'https://dzrgcyhovmomyoztzmoq.supabase.co/storage/v1/object/public/character-images/Kankurou.png' WHERE character_name = 'Kankurou';
UPDATE character_images SET image_url = 'https://dzrgcyhovmomyoztzmoq.supabase.co/storage/v1/object/public/character-images/Kankurou SHP.png' WHERE character_name = 'Kankurou Shippūden';
UPDATE character_images SET image_url = 'https://dzrgcyhovmomyoztzmoq.supabase.co/storage/v1/object/public/character-images/Kiba SHP.png' WHERE character_name = 'Kiba Inuzuka Shippūden';
UPDATE character_images SET image_url = 'https://dzrgcyhovmomyoztzmoq.supabase.co/storage/v1/object/public/character-images/Kidoumaru.png' WHERE character_name = 'Kidoumaru';
UPDATE character_images SET image_url = 'https://dzrgcyhovmomyoztzmoq.supabase.co/storage/v1/object/public/character-images/Kimimaro.png' WHERE character_name = 'Kimimaro';
UPDATE character_images SET image_url = 'https://dzrgcyhovmomyoztzmoq.supabase.co/storage/v1/object/public/character-images/Konohamaru.png' WHERE character_name = 'Konohamaru';
UPDATE character_images SET image_url = 'https://dzrgcyhovmomyoztzmoq.supabase.co/storage/v1/object/public/character-images/Kurenai.png' WHERE character_name = 'Kurenai Yuuhi';
UPDATE character_images SET image_url = 'https://dzrgcyhovmomyoztzmoq.supabase.co/storage/v1/object/public/character-images/Might Guy.png' WHERE character_name = 'Might Guy';
UPDATE character_images SET image_url = 'https://dzrgcyhovmomyoztzmoq.supabase.co/storage/v1/object/public/character-images/Minato.png' WHERE character_name = 'Minato Namikaze';
UPDATE character_images SET image_url = 'https://dzrgcyhovmomyoztzmoq.supabase.co/storage/v1/object/public/character-images/Neji SHP.png' WHERE character_name = 'Neji Hyuuga Shippūden';
UPDATE character_images SET image_url = 'https://dzrgcyhovmomyoztzmoq.supabase.co/storage/v1/object/public/character-images/Rock Lee Lv2.png' WHERE character_name = 'Rock Lee Modo Punho Zonzo';
UPDATE character_images SET image_url = 'https://dzrgcyhovmomyoztzmoq.supabase.co/storage/v1/object/public/character-images/Sai.png' WHERE character_name = 'Sai';
UPDATE character_images SET image_url = 'https://dzrgcyhovmomyoztzmoq.supabase.co/storage/v1/object/public/character-images/Sakon e Ukon.png' WHERE character_name = 'Sakon e Ukon';
UPDATE character_images SET image_url = 'https://dzrgcyhovmomyoztzmoq.supabase.co/storage/v1/object/public/character-images/Sakura SHP.png' WHERE character_name = 'Sakura Haruno Shippūden';
UPDATE character_images SET image_url = 'https://dzrgcyhovmomyoztzmoq.supabase.co/storage/v1/object/public/character-images/Shikamaru SHP.png' WHERE character_name = 'Shikamaru Nara Shippūden';
UPDATE character_images SET image_url = 'https://dzrgcyhovmomyoztzmoq.supabase.co/storage/v1/object/public/character-images/Shino SHP.png' WHERE character_name = 'Shino Aburame Shippūden';
UPDATE character_images SET image_url = 'https://dzrgcyhovmomyoztzmoq.supabase.co/storage/v1/object/public/character-images/Shizune.png' WHERE character_name = 'Shizune';
UPDATE character_images SET image_url = 'https://dzrgcyhovmomyoztzmoq.supabase.co/storage/v1/object/public/character-images/Tayuya.png' WHERE character_name = 'Tayuya';
UPDATE character_images SET image_url = 'https://dzrgcyhovmomyoztzmoq.supabase.co/storage/v1/object/public/character-images/Temari.png' WHERE character_name = 'Temari';
UPDATE character_images SET image_url = 'https://dzrgcyhovmomyoztzmoq.supabase.co/storage/v1/object/public/character-images/Temari SHP.png' WHERE character_name = 'Temari Shippūden';
UPDATE character_images SET image_url = 'https://dzrgcyhovmomyoztzmoq.supabase.co/storage/v1/object/public/character-images/Terceiro Kazekage.png' WHERE character_name = 'Terceiro Kazekage';
UPDATE character_images SET image_url = 'https://dzrgcyhovmomyoztzmoq.supabase.co/storage/v1/object/public/character-images/Tobirama.png' WHERE character_name = 'Tobirama Senju';
UPDATE character_images SET image_url = 'https://dzrgcyhovmomyoztzmoq.supabase.co/storage/v1/object/public/character-images/Vovó Chiyo.png' WHERE character_name = 'Vovó Chiyo';
UPDATE character_images SET image_url = 'https://dzrgcyhovmomyoztzmoq.supabase.co/storage/v1/object/public/character-images/Vovó Chiyo Lv2.png' WHERE character_name = 'Vovó Chiyo Taijutsu';
UPDATE character_images SET image_url = 'https://dzrgcyhovmomyoztzmoq.supabase.co/storage/v1/object/public/character-images/Vovó Chiyo(Hiruko).png' WHERE character_name = 'Vovó Chiyo Mestre das Marionetes';
UPDATE character_images SET image_url = 'https://dzrgcyhovmomyoztzmoq.supabase.co/storage/v1/object/public/character-images/Yamato.png' WHERE character_name = 'Yamato';
UPDATE character_images SET image_url = 'https://dzrgcyhovmomyoztzmoq.supabase.co/storage/v1/object/public/character-images/Zabuza.png' WHERE character_name = 'Zabuza Momochi';