-- Restore backend seed and API grants for Kage Arena.
-- Generated from src/data/academyCharacters.ts and src/data/characterImages.ts.

-- New Supabase projects may not expose public tables/functions automatically.
-- Keep grants explicit so supabase-js can reach the intended API surface while RLS controls rows.
GRANT SELECT ON
  public.players,
  public.banners,
  public.achievements,
  public.evaluations,
  public.challenges,
  public.matches,
  public.ranking_changes,
  public.tournaments,
  public.tournament_participants,
  public.tournament_matches,
  public.tournament_rewards
TO anon;

GRANT SELECT, INSERT, UPDATE, DELETE ON
  public.players,
  public.banners,
  public.player_banners,
  public.achievements,
  public.player_achievements,
  public.redemption_codes,
  public.redeemed_codes,
  public.evaluations,
  public.evaluation_results,
  public.challenges,
  public.matches,
  public.ranking_changes,
  public.tournaments,
  public.tournament_participants,
  public.tournament_matches,
  public.tournament_rewards,
  public.notifications
TO authenticated;

GRANT ALL ON
  public.players,
  public.banners,
  public.player_banners,
  public.achievements,
  public.player_achievements,
  public.redemption_codes,
  public.redeemed_codes,
  public.evaluations,
  public.evaluation_results,
  public.challenges,
  public.matches,
  public.ranking_changes,
  public.tournaments,
  public.tournament_participants,
  public.tournament_matches,
  public.tournament_rewards,
  public.notifications
TO service_role;

GRANT SELECT ON public.forum_categories TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.forum_categories TO authenticated;
GRANT ALL ON public.forum_categories TO service_role;
GRANT SELECT ON public.forum_topics TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.forum_topics TO authenticated;
GRANT ALL ON public.forum_topics TO service_role;
GRANT SELECT ON public.forum_replies TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.forum_replies TO authenticated;
GRANT ALL ON public.forum_replies TO service_role;
GRANT SELECT ON public.forum_reactions TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.forum_reactions TO authenticated;
GRANT ALL ON public.forum_reactions TO service_role;
GRANT SELECT ON public.tournament_disputes TO authenticated;
GRANT INSERT, UPDATE, DELETE ON public.tournament_disputes TO authenticated;
GRANT ALL ON public.tournament_disputes TO service_role;

GRANT EXECUTE ON FUNCTION public.can_update_profile_settings(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.redeem_code(uuid, varchar) TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_kage_titles() TO authenticated;
GRANT EXECUTE ON FUNCTION public.advance_tournament_winner(uuid, uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.generate_tournament_bracket(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.finalize_tournament(uuid) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_player_available_banners(uuid) TO authenticated, anon;

-- Final banner/code seed adapted to the current banners schema.
INSERT INTO public.achievements (name, display_name, description, icon, color, category)
VALUES ('bucha_elite', 'Bucha de Elite', 'Conquistado por membros fundadores da comunidade', 'award', 'gold', 'special')
ON CONFLICT (name) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  icon = EXCLUDED.icon,
  color = EXCLUDED.color,
  category = EXCLUDED.category;

INSERT INTO public.banners (name, display_name, description, image_url, rarity, category, is_available, unlock_type)
VALUES ('legacy_banner', 'Banner Legado', 'Banner comemorativo de lancamento do site', '', 'rare', 'event', true, 'code')
ON CONFLICT (name) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  description = EXCLUDED.description,
  rarity = EXCLUDED.rarity,
  category = EXCLUDED.category,
  is_available = EXCLUDED.is_available,
  unlock_type = EXCLUDED.unlock_type;

INSERT INTO public.redemption_codes (code, banner_id, achievement_id, max_uses, is_active)
SELECT 'eusoubuchad+', b.id, a.id, NULL, true
FROM public.banners b
CROSS JOIN public.achievements a
WHERE b.name = 'legacy_banner'
  AND a.name = 'bucha_elite'
ON CONFLICT (code) DO UPDATE SET
  banner_id = EXCLUDED.banner_id,
  achievement_id = EXCLUDED.achievement_id,
  max_uses = EXCLUDED.max_uses,
  is_active = EXCLUDED.is_active;

CREATE UNIQUE INDEX IF NOT EXISTS uq_academy_moves_character_name_type
  ON public.academy_character_moves (character_id, name, move_type);

INSERT INTO public.academy_characters (
  slug, name, tier, image_url, image_lv2_url, short_description, full_description,
  playstyle, difficulty, attributes, strengths, weaknesses, favorable_against,
  unfavorable_against, recommended_for, is_published, is_featured, sort_order
)
VALUES
('naruto-uzumaki', 'Naruto Uzumaki', 'S+', '/characters/naruto-pts.png', '/characters/naruto-pts-lv2.png', 'O jovem Naruto possui um kit versátil com clones de sombra e Rasengan.', 'O jovem Naruto possui um kit versátil com clones de sombra e Rasengan. Excelente em mixups e pressão constante. Ideal para jogadores que gostam de agressão controlada com múltiplas opções de ataque.', 'Tecnica', 'expert', '{"strength":8,"speed":7,"technique":9,"defense":6,"mobility":8,"versatility":9}'::jsonb, ARRAY['Tecnicas fortes','Kit versatil','Dano alto']::text[], ARRAY['Defesa vulneravel','Velocidade menor']::text[], ARRAY['Rock Lee','Gaara','Neji Hyuuga']::text[], ARRAY['Itachi Uchiha','Sasuke Shippūden','Minato Namikaze']::text[], 'Jogadores avancados', true, true, 1),
('naruto-shippuden', 'Naruto Shippūden', 'S+', '/characters/naruto-ts.png', '/characters/naruto-ts-lv2.png', 'Naruto mais maduro com Rasen Shuriken e modo Sennin.', 'Naruto mais maduro com Rasen Shuriken e modo Sennin. Arsenal completo para todas as situações. Top tier absoluto nas mãos certas.', 'Tecnica', 'expert', '{"strength":9,"speed":8,"technique":10,"defense":7,"mobility":9,"versatility":10}'::jsonb, ARRAY['Tecnicas fortes','Kit versatil','Dano alto']::text[], ARRAY['Defesa vulneravel','Velocidade menor']::text[], ARRAY['Sasuke Uchiha','Orochimaru','Kabuto Yakushi']::text[], ARRAY['Itachi Uchiha','Minato Namikaze','Hashirama Senju']::text[], 'Jogadores avancados', true, true, 2),
('sasuke-uchiha', 'Sasuke Uchiha', 'S', '/characters/sasuke-pts.png', '/characters/sasuke-pts-lv2.png', 'O último dos Uchiha combina velocidade mortal com técnicas poderosas.', 'O último dos Uchiha combina velocidade mortal com técnicas poderosas. Sharingan permite counters precisos. Chidori oferece alto dano em punishes.', 'Velocidade', 'expert', '{"strength":7,"speed":9,"technique":9,"defense":5,"mobility":9,"versatility":8}'::jsonb, ARRAY['Velocidade acima da media','Tecnicas fortes','Mobilidade forte']::text[], ARRAY['Defesa vulneravel','Dano base menor']::text[], ARRAY['Sakura Haruno','Hinata Hyuuga','Shikamaru Nara']::text[], ARRAY['Naruto Shippūden','Itachi Uchiha','Minato Namikaze']::text[], 'Jogadores avancados', true, true, 3),
('sasuke-shippuden', 'Sasuke Shippūden', 'S+', '/characters/sasuke-ts.png', NULL, 'Sasuke no auge com Mangekyo Sharingan.', 'Sasuke no auge com Mangekyo Sharingan. Amaterasu, Susanoo e Kirin formam arsenal devastador. Mobilidade extrema e dano consistente.', 'Velocidade', 'expert', '{"strength":8,"speed":10,"technique":10,"defense":6,"mobility":10,"versatility":9}'::jsonb, ARRAY['Velocidade acima da media','Tecnicas fortes','Mobilidade forte']::text[], ARRAY['Defesa vulneravel','Dano base menor']::text[], ARRAY['Orochimaru','Deidara','Kabuto Yakushi']::text[], ARRAY['Naruto Shippūden','Itachi Uchiha','Hashirama Senju']::text[], 'Jogadores avancados', true, true, 4),
('itachi-uchiha', 'Itachi Uchiha', 'S', '/characters/itachi.png', NULL, 'Gênio tático com arsenal devastador.', 'Gênio tático com arsenal devastador. Tsukuyomi controla mente, Amaterasu queima tudo, Susanoo protege. Domina através de leitura e timing perfeito.', 'Tecnica', 'expert', '{"strength":6,"speed":8,"technique":10,"defense":6,"mobility":7,"versatility":9}'::jsonb, ARRAY['Tecnicas fortes','Kit versatil','Velocidade acima da media']::text[], ARRAY['Dano base menor','Defesa vulneravel']::text[], ARRAY['Naruto Uzumaki','Jiraiya','Orochimaru']::text[], ARRAY['Sasuke Shippūden','Minato Namikaze','Hashirama Senju']::text[], 'Jogadores avancados', true, true, 5),
('minato-namikaze', 'Minato Namikaze', 'S', '/characters/4-hokage.png', NULL, 'O Relâmpago Amarelo de Konoha.', 'O Relâmpago Amarelo de Konoha. Velocidade incomparável com Hiraishin. Rasengan preciso e teleporte constante. Domina neutral e punishes.', 'Velocidade', 'expert', '{"strength":7,"speed":10,"technique":10,"defense":5,"mobility":10,"versatility":9}'::jsonb, ARRAY['Velocidade acima da media','Tecnicas fortes','Mobilidade forte']::text[], ARRAY['Defesa vulneravel','Dano base menor']::text[], ARRAY['Sasuke Uchiha','Orochimaru','Kisame Hoshigaki']::text[], ARRAY['Hashirama Senju','Tobirama Senju','Itachi Uchiha']::text[], 'Jogadores avancados', true, true, 6),
('kakashi-hatake', 'Kakashi Hatake', 'A+', '/characters/kakashi.png', NULL, 'O Ninja Copiador possui toolkit mais versátil do jogo.', 'O Ninja Copiador possui toolkit mais versátil do jogo. Sharingan, Raikiri e diversos jutsus copiados. Excelente em neutral e footsies.', 'Tecnica', 'hard', '{"strength":7,"speed":8,"technique":10,"defense":7,"mobility":7,"versatility":10}'::jsonb, ARRAY['Tecnicas fortes','Kit versatil','Velocidade acima da media']::text[], ARRAY['Dano base menor','Defesa vulneravel']::text[], ARRAY['Deidara','Sasori','Hidan']::text[], ARRAY['Itachi Uchiha','Minato Namikaze','Hashirama Senju']::text[], 'Todos os jogadores', true, true, 7),
('jiraiya', 'Jiraiya', 'A+', '/characters/jiraya.png', NULL, 'O Sannin Sapo com arsenal massivo.', 'O Sannin Sapo com arsenal massivo. Rasengan, invocações e modo Sennin. Excelente em zoning e setups elaborados. Recompensa paciência.', 'Tecnica', 'hard', '{"strength":8,"speed":6,"technique":9,"defense":7,"mobility":6,"versatility":9}'::jsonb, ARRAY['Tecnicas fortes','Kit versatil','Dano alto']::text[], ARRAY['Velocidade menor','Mobilidade limitada']::text[], ARRAY['Orochimaru','Kabuto Yakushi','Kisame Hoshigaki']::text[], ARRAY['Itachi Uchiha','Minato Namikaze','Naruto Shippūden']::text[], 'Todos os jogadores', true, true, 8),
('tsunade', 'Tsunade', 'A+', '/characters/tsunade.png', NULL, 'A Sannin Médica com força monstruosa.', 'A Sannin Médica com força monstruosa. Golpes devastadores que quebram guarda. Regeneração permite trades favoráveis. Tank com explosão.', 'Pressao e dano', 'hard', '{"strength":10,"speed":6,"technique":8,"defense":9,"mobility":5,"versatility":7}'::jsonb, ARRAY['Dano alto','Boa defesa','Tecnicas fortes']::text[], ARRAY['Mobilidade limitada','Velocidade menor']::text[], ARRAY['Orochimaru','Kabuto Yakushi','Kimimaro']::text[], ARRAY['Itachi Uchiha','Minato Namikaze','Deidara']::text[], 'Todos os jogadores', true, false, 9),
('orochimaru', 'Orochimaru', 'A+', '/characters/orochimaru.png', NULL, 'O Sannin das Cobras com kit único.', 'O Sannin das Cobras com kit único. Alcance extremo, invocações e jutsus proibidos. Zoning master que frustra approach.', 'Tecnica', 'hard', '{"strength":6,"speed":7,"technique":10,"defense":6,"mobility":8,"versatility":10}'::jsonb, ARRAY['Tecnicas fortes','Kit versatil','Mobilidade forte']::text[], ARRAY['Dano base menor','Defesa vulneravel']::text[], ARRAY['Sakura Haruno','Rock Lee','Kiba Inuzuka']::text[], ARRAY['Jiraiya','Tsunade','Naruto Shippūden']::text[], 'Todos os jogadores', true, false, 10),
('hashirama-senju', 'Hashirama Senju', 'S', '/characters/1-hokage.png', NULL, 'O Deus dos Shinobi.', 'O Deus dos Shinobi. Wood Release domina o cenário com controle de área incomparável. Força bruta combinada com versatilidade técnica.', 'Pressao e dano', 'expert', '{"strength":10,"speed":7,"technique":10,"defense":9,"mobility":6,"versatility":10}'::jsonb, ARRAY['Dano alto','Tecnicas fortes','Kit versatil']::text[], ARRAY['Mobilidade limitada','Velocidade menor']::text[], ARRAY['Minato Namikaze','Itachi Uchiha','Orochimaru']::text[], ARRAY['Tobirama Senju','Naruto Shippūden']::text[], 'Jogadores avancados', true, false, 11),
('tobirama-senju', 'Tobirama Senju', 'A+', '/characters/2-hokage.png', NULL, 'O Segundo Hokage.', 'O Segundo Hokage. Water Release devastador e Hiraishin original. Técnico com excelente controle de espaço e mobilidade.', 'Tecnica', 'hard', '{"strength":8,"speed":9,"technique":10,"defense":7,"mobility":9,"versatility":9}'::jsonb, ARRAY['Tecnicas fortes','Velocidade acima da media','Mobilidade forte']::text[], ARRAY['Defesa vulneravel','Dano base menor']::text[], ARRAY['Hashirama Senju','Orochimaru','Kisame Hoshigaki']::text[], ARRAY['Minato Namikaze','Itachi Uchiha']::text[], 'Todos os jogadores', true, false, 12),
('hiruzen-sarutobi', 'Hiruzen Sarutobi', 'A', '/characters/3-hokage.png', NULL, 'O Professor.', 'O Professor. Conhece todos os jutsus de Konoha. Kit extremamente versátil mas requer alto conhecimento. Jack of all trades.', 'Tecnica', 'hard', '{"strength":7,"speed":6,"technique":10,"defense":7,"mobility":6,"versatility":10}'::jsonb, ARRAY['Tecnicas fortes','Kit versatil','Dano alto']::text[], ARRAY['Velocidade menor','Mobilidade limitada']::text[], ARRAY['Orochimaru','Kabuto Yakushi','Sound Four']::text[], ARRAY['Itachi Uchiha','Minato Namikaze','Hashirama Senju']::text[], 'Todos os jogadores', true, false, 13),
('rock-lee', 'Rock Lee', 'A', '/characters/lee-pts.png', '/characters/lee-lv2.png', 'Velocidade pura e taijutsu devastador.', 'Velocidade pura e taijutsu devastador. Não usa ninjutsu mas compensa com agilidade extrema. Rushdown implacável que não dá respiro.', 'Velocidade', 'hard', '{"strength":9,"speed":10,"technique":6,"defense":5,"mobility":10,"versatility":5}'::jsonb, ARRAY['Velocidade acima da media','Mobilidade forte','Dano alto']::text[], ARRAY['Defesa vulneravel','Menos opcoes situacionais']::text[], ARRAY['Tenten','Kiba Inuzuka','Chouji Akimichi']::text[], ARRAY['Gaara','Neji Hyuuga','Temari']::text[], 'Todos os jogadores', true, false, 14),
('rock-lee-modo-punho-zonzo', 'Rock Lee Modo Punho Zonzo', 'A+', '/characters/lee-lv2.png', NULL, 'Lee bêbado com movimentos imprevisíveis.', 'Lee bêbado com movimentos imprevisíveis. Stance única que confunde oponentes. Alta skill cap mas extremamente recompensador.', 'Velocidade', 'hard', '{"strength":8,"speed":10,"technique":8,"defense":4,"mobility":10,"versatility":7}'::jsonb, ARRAY['Velocidade acima da media','Mobilidade forte','Dano alto']::text[], ARRAY['Defesa vulneravel','Menos opcoes situacionais']::text[], ARRAY['Neji Hyuuga','Shikamaru Nara','Gaara']::text[], ARRAY['Itachi Uchiha','Kakashi Hatake','Minato Namikaze']::text[], 'Todos os jogadores', true, false, 15),
('rock-lee-shippuden', 'Rock Lee Shippūden', 'A', '/characters/lee-ts.png', NULL, 'Lee mais maduro com taijutsu refinado.', 'Lee mais maduro com taijutsu refinado. Velocidade mantida com mais consistência. Menos volátil que versões anteriores.', 'Velocidade', 'hard', '{"strength":9,"speed":10,"technique":7,"defense":6,"mobility":10,"versatility":6}'::jsonb, ARRAY['Velocidade acima da media','Mobilidade forte','Dano alto']::text[], ARRAY['Defesa vulneravel','Menos opcoes situacionais']::text[], ARRAY['Deidara','Sasori','Kankurou']::text[], ARRAY['Gaara Shippūden','Neji Hyuuga Shippūden','Temari Shippūden']::text[], 'Todos os jogadores', true, false, 16),
('neji-hyuuga', 'Neji Hyuuga', 'A', '/characters/neji-pts.png', NULL, 'Gênio Hyuuga com Byakugan.', 'Gênio Hyuuga com Byakugan. Gentle Fist fecha tenketsu e drena chakra. Rotation oferece defesa perfeita. Técnico e preciso.', 'Tecnica', 'hard', '{"strength":7,"speed":8,"technique":9,"defense":8,"mobility":7,"versatility":7}'::jsonb, ARRAY['Tecnicas fortes','Velocidade acima da media','Boa defesa']::text[], ARRAY['Dano base menor','Mobilidade limitada']::text[], ARRAY['Rock Lee','Kiba Inuzuka','Naruto Uzumaki']::text[], ARRAY['Itachi Uchiha','Kakashi Hatake','Sasuke Shippūden']::text[], 'Todos os jogadores', true, false, 17),
('neji-hyuuga-shippuden', 'Neji Hyuuga Shippūden', 'A+', '/characters/neji-ts.png', NULL, 'Neji amadurecido com técnicas refinadas.', 'Neji amadurecido com técnicas refinadas. Gentle Fist mais poderoso e Rotation melhorado. Mais completo que versão original.', 'Tecnica', 'hard', '{"strength":8,"speed":8,"technique":10,"defense":8,"mobility":7,"versatility":8}'::jsonb, ARRAY['Tecnicas fortes','Dano alto','Velocidade acima da media']::text[], ARRAY['Mobilidade limitada','Dano base menor']::text[], ARRAY['Rock Lee Shippūden','Kiba Inuzuka Shippūden','Hinata Hyuuga Shippūden']::text[], ARRAY['Itachi Uchiha','Sasuke Shippūden','Naruto Shippūden']::text[], 'Todos os jogadores', true, false, 18),
('gaara', 'Gaara', 'A', '/characters/gaara-pts.png', '/characters/gaara-pts-lv2.png', 'Mestre da defesa absoluta.', 'Mestre da defesa absoluta. Areia protege automaticamente e contra-ataca. Excelente em zoning e controle de espaço.', 'Defesa', 'hard', '{"strength":6,"speed":5,"technique":8,"defense":10,"mobility":6,"versatility":8}'::jsonb, ARRAY['Boa defesa','Tecnicas fortes','Kit versatil']::text[], ARRAY['Velocidade menor','Dano base menor']::text[], ARRAY['Rock Lee','Kiba Inuzuka','Sakura Haruno']::text[], ARRAY['Deidara','Sasuke Uchiha','Naruto Shippūden']::text[], 'Todos os jogadores', true, false, 19),
('gaara-shippuden', 'Gaara Shippūden', 'A+', '/characters/gaara-ts.png', NULL, 'Kazekage com controle de areia refinado.', 'Kazekage com controle de areia refinado. Mais versátil e técnico. Defesa mantida com mais opções ofensivas.', 'Defesa', 'hard', '{"strength":7,"speed":6,"technique":9,"defense":10,"mobility":7,"versatility":9}'::jsonb, ARRAY['Boa defesa','Tecnicas fortes','Kit versatil']::text[], ARRAY['Velocidade menor','Dano base menor']::text[], ARRAY['Rock Lee Shippūden','Kiba Inuzuka Shippūden','Deidara']::text[], ARRAY['Sasuke Shippūden','Naruto Shippūden','Itachi Uchiha']::text[], 'Todos os jogadores', true, false, 20),
('might-guy', 'Might Guy', 'A+', '/characters/guy.png', NULL, 'Mestre do Taijutsu e dos 8 Portões.', 'Mestre do Taijutsu e dos 8 Portões. Lee mais forte e consistente. Explosivo com dano absurdo quando ativa portões.', 'Pressao e dano', 'hard', '{"strength":10,"speed":9,"technique":7,"defense":6,"mobility":9,"versatility":6}'::jsonb, ARRAY['Dano alto','Velocidade acima da media','Mobilidade forte']::text[], ARRAY['Defesa vulneravel','Menos opcoes situacionais']::text[], ARRAY['Kisame Hoshigaki','Deidara','Sasori']::text[], ARRAY['Itachi Uchiha','Minato Namikaze','Hashirama Senju']::text[], 'Todos os jogadores', true, false, 21),
('sakura-haruno', 'Sakura Haruno', 'B+', '/characters/sakura-pts.png', NULL, 'Sakura jovem com kit básico.', 'Sakura jovem com kit básico. Socos fortes mas kit limitado. Boa para iniciantes aprenderem fundamentos.', 'Tecnica', 'medium', '{"strength":6,"speed":6,"technique":7,"defense":5,"mobility":6,"versatility":6}'::jsonb, ARRAY['Tecnicas fortes','Dano alto','Velocidade acima da media']::text[], ARRAY['Defesa vulneravel','Dano base menor']::text[], ARRAY['Ino Yamanaka','Tenten','Konohamaru']::text[], ARRAY['Sasuke Uchiha','Naruto Uzumaki','Rock Lee']::text[], 'Todos os jogadores', true, false, 22),
('sakura-haruno-shippuden', 'Sakura Haruno Shippūden', 'A', '/characters/sakura-ts.png', NULL, 'Sakura treinada por Tsunade.', 'Sakura treinada por Tsunade. Força monstruosa com cura. Mais completa e viável competitivamente.', 'Pressao e dano', 'hard', '{"strength":9,"speed":7,"technique":8,"defense":7,"mobility":6,"versatility":7}'::jsonb, ARRAY['Dano alto','Tecnicas fortes','Velocidade acima da media']::text[], ARRAY['Mobilidade limitada','Velocidade menor']::text[], ARRAY['Ino Yamanaka Shippūden','Sasori','Kabuto Yakushi']::text[], ARRAY['Sasuke Shippūden','Naruto Shippūden','Itachi Uchiha']::text[], 'Todos os jogadores', true, false, 23),
('shikamaru-nara', 'Shikamaru Nara', 'B+', '/characters/shikamaru-pts.png', NULL, 'Gênio estratégico com Shadow Possession.', 'Gênio estratégico com Shadow Possession. Baixo dano mas controle extremo. Recompensa paciência e leitura.', 'Tecnica', 'medium', '{"strength":4,"speed":5,"technique":10,"defense":5,"mobility":5,"versatility":8}'::jsonb, ARRAY['Tecnicas fortes','Kit versatil','Velocidade acima da media']::text[], ARRAY['Dano base menor','Velocidade menor']::text[], ARRAY['Hidan','Temari','Ino Yamanaka']::text[], ARRAY['Rock Lee','Naruto Uzumaki','Kiba Inuzuka']::text[], 'Todos os jogadores', true, false, 24),
('shikamaru-nara-shippuden', 'Shikamaru Nara Shippūden', 'A', '/characters/shikamaru-ts.png', NULL, 'Shikamaru mais experiente.', 'Shikamaru mais experiente. Sombras mais versáteis e estratégias refinadas. Melhor em todos os aspectos.', 'Tecnica', 'hard', '{"strength":5,"speed":6,"technique":10,"defense":6,"mobility":6,"versatility":9}'::jsonb, ARRAY['Tecnicas fortes','Kit versatil','Velocidade acima da media']::text[], ARRAY['Dano base menor','Velocidade menor']::text[], ARRAY['Hidan','Deidara','Temari Shippūden']::text[], ARRAY['Naruto Shippūden','Rock Lee Shippūden','Might Guy']::text[], 'Todos os jogadores', true, false, 25),
('chouji-akimichi', 'Chouji Akimichi', 'B', '/characters/chouji-pts.png', '/characters/chouji-lv2.png', 'Tank pesado com expansão corporal.', 'Tank pesado com expansão corporal. Lento mas forte. Bom para quem gosta de trades e pressão física.', 'Pressao e dano', 'medium', '{"strength":9,"speed":4,"technique":5,"defense":8,"mobility":4,"versatility":5}'::jsonb, ARRAY['Dano alto','Boa defesa','Tecnicas fortes']::text[], ARRAY['Velocidade menor','Mobilidade limitada']::text[], ARRAY['Ino Yamanaka','Shino Aburame','Hinata Hyuuga']::text[], ARRAY['Rock Lee','Naruto Uzumaki','Sasuke Uchiha']::text[], 'Todos os jogadores', true, false, 26),
('chouji-akimichi-shippuden', 'Chouji Akimichi Shippūden', 'B+', '/characters/chouji-ts.png', NULL, 'Chouji mais forte com Butterfly Mode.', 'Chouji mais forte com Butterfly Mode. Ainda lento mas dano compensar. Tank que pode virar partidas.', 'Pressao e dano', 'medium', '{"strength":10,"speed":5,"technique":6,"defense":9,"mobility":5,"versatility":6}'::jsonb, ARRAY['Dano alto','Boa defesa','Tecnicas fortes']::text[], ARRAY['Velocidade menor','Mobilidade limitada']::text[], ARRAY['Ino Yamanaka Shippūden','Shino Aburame Shippūden','Kankurou Shippūden']::text[], ARRAY['Rock Lee Shippūden','Naruto Shippūden','Sasuke Shippūden']::text[], 'Todos os jogadores', true, false, 27),
('ino-yamanaka', 'Ino Yamanaka', 'C+', '/characters/ino-pts.png', NULL, 'Especialista em jutsu mental.', 'Especialista em jutsu mental. Mind Transfer arriscado mas devastador. Tier baixo mas gimmick forte.', 'Tecnica', 'easy', '{"strength":4,"speed":6,"technique":7,"defense":4,"mobility":6,"versatility":6}'::jsonb, ARRAY['Tecnicas fortes','Velocidade acima da media','Mobilidade forte']::text[], ARRAY['Dano base menor','Defesa vulneravel']::text[], ARRAY['Tenten','Konohamaru','Hanabi Hyuuga']::text[], ARRAY['Shikamaru Nara','Sakura Haruno','Naruto Uzumaki']::text[], 'Todos os jogadores', true, false, 28),
('ino-yamanaka-shippuden', 'Ino Yamanaka Shippūden', 'B', '/characters/ino-ts.png', NULL, 'Ino melhorada com habilidades médicas.', 'Ino melhorada com habilidades médicas. Mind Transfer mais seguro. Mais viável que versão original.', 'Tecnica', 'medium', '{"strength":5,"speed":7,"technique":8,"defense":5,"mobility":7,"versatility":7}'::jsonb, ARRAY['Tecnicas fortes','Velocidade acima da media','Mobilidade forte']::text[], ARRAY['Dano base menor','Defesa vulneravel']::text[], ARRAY['Tenten Shippūden','Konohamaru','Shino Aburame']::text[], ARRAY['Shikamaru Nara Shippūden','Sakura Haruno Shippūden','Chouji Akimichi Shippūden']::text[], 'Todos os jogadores', true, false, 29),
('asuma-sarutobi', 'Asuma Sarutobi', 'B+', '/characters/assuma.png', NULL, 'Jounin equilibrado com chakra blades.', 'Jounin equilibrado com chakra blades. Sólido em todas as áreas sem brilhar em nenhuma. Bom para fundamentos.', 'Pressao e dano', 'medium', '{"strength":8,"speed":7,"technique":7,"defense":7,"mobility":6,"versatility":7}'::jsonb, ARRAY['Dano alto','Velocidade acima da media','Tecnicas fortes']::text[], ARRAY['Mobilidade limitada','Velocidade menor']::text[], ARRAY['Hidan','Shikamaru Nara','Ino Yamanaka']::text[], ARRAY['Itachi Uchiha','Kakashi Hatake','Minato Namikaze']::text[], 'Todos os jogadores', true, false, 30),
('shino-aburame', 'Shino Aburame', 'B', '/characters/shino-pts.png', NULL, 'Controlador de insetos único.', 'Controlador de insetos único. Drena chakra e cria armadilhas. Jogo paciênte de atrito.', 'Tecnica', 'medium', '{"strength":5,"speed":5,"technique":8,"defense":6,"mobility":5,"versatility":7}'::jsonb, ARRAY['Tecnicas fortes','Kit versatil','Boa defesa']::text[], ARRAY['Dano base menor','Velocidade menor']::text[], ARRAY['Ino Yamanaka','Tenten','Konohamaru']::text[], ARRAY['Rock Lee','Sasuke Uchiha','Naruto Uzumaki']::text[], 'Todos os jogadores', true, false, 31),
('shino-aburame-shippuden', 'Shino Aburame Shippūden', 'B+', '/characters/shino-ts.png', NULL, 'Shino mais poderoso.', 'Shino mais poderoso. Insetos mais versáteis e controle aprimorado. Melhor em zoning.', 'Tecnica', 'medium', '{"strength":6,"speed":6,"technique":9,"defense":7,"mobility":6,"versatility":8}'::jsonb, ARRAY['Tecnicas fortes','Kit versatil','Boa defesa']::text[], ARRAY['Dano base menor','Velocidade menor']::text[], ARRAY['Ino Yamanaka Shippūden','Tenten Shippūden','Kankurou Shippūden']::text[], ARRAY['Rock Lee Shippūden','Sasuke Shippūden','Naruto Shippūden']::text[], 'Todos os jogadores', true, false, 32),
('kiba-inuzuka', 'Kiba Inuzuka', 'B', '/characters/kiba-pts.png', NULL, 'Rushdown com Akamaru.', 'Rushdown com Akamaru. Rápido mas previsível. Bom para iniciantes que gostam de agressão.', 'Velocidade', 'medium', '{"strength":7,"speed":8,"technique":5,"defense":5,"mobility":8,"versatility":5}'::jsonb, ARRAY['Velocidade acima da media','Mobilidade forte','Dano alto']::text[], ARRAY['Execucao mais limitada','Defesa vulneravel']::text[], ARRAY['Shino Aburame','Ino Yamanaka','Tenten']::text[], ARRAY['Neji Hyuuga','Gaara','Shikamaru Nara']::text[], 'Todos os jogadores', true, false, 33),
('kiba-inuzuka-shippuden', 'Kiba Inuzuka Shippūden', 'B+', '/characters/kiba-ts.png', NULL, 'Kiba mais forte com técnicas aprimoradas.', 'Kiba mais forte com técnicas aprimoradas. Akamaru maior e mais poderoso. Rushdown melhorado.', 'Velocidade', 'medium', '{"strength":8,"speed":9,"technique":6,"defense":6,"mobility":9,"versatility":6}'::jsonb, ARRAY['Velocidade acima da media','Mobilidade forte','Dano alto']::text[], ARRAY['Execucao mais limitada','Defesa vulneravel']::text[], ARRAY['Shino Aburame Shippūden','Ino Yamanaka Shippūden','Tenten Shippūden']::text[], ARRAY['Neji Hyuuga Shippūden','Gaara Shippūden','Shikamaru Nara Shippūden']::text[], 'Todos os jogadores', true, false, 34),
('hinata-hyuuga', 'Hinata Hyuuga', 'B', '/characters/hinata-pts.png', NULL, 'Gentle Fist tímido.', 'Gentle Fist tímido. Técnica boa mas menos agressiva que Neji. Defensiva com contra-ataques.', 'Tecnica', 'medium', '{"strength":5,"speed":6,"technique":8,"defense":6,"mobility":6,"versatility":6}'::jsonb, ARRAY['Tecnicas fortes','Velocidade acima da media','Boa defesa']::text[], ARRAY['Dano base menor','Velocidade menor']::text[], ARRAY['Ino Yamanaka','Tenten','Konohamaru']::text[], ARRAY['Neji Hyuuga','Sasuke Uchiha','Rock Lee']::text[], 'Todos os jogadores', true, false, 35),
('hinata-hyuuga-shippuden', 'Hinata Hyuuga Shippūden', 'B+', '/characters/hinata-ts.png', NULL, 'Hinata mais confiante.', 'Hinata mais confiante. Gentle Fist aprimorado com Twin Lions. Mais viável competitivamente.', 'Tecnica', 'medium', '{"strength":6,"speed":7,"technique":9,"defense":7,"mobility":7,"versatility":7}'::jsonb, ARRAY['Tecnicas fortes','Velocidade acima da media','Boa defesa']::text[], ARRAY['Dano base menor','Velocidade menor']::text[], ARRAY['Ino Yamanaka Shippūden','Tenten Shippūden','Kankurou Shippūden']::text[], ARRAY['Neji Hyuuga Shippūden','Sasuke Shippūden','Rock Lee Shippūden']::text[], 'Todos os jogadores', true, false, 36),
('kurenai-yuuhi', 'Kurenai Yuuhi', 'B', '/characters/kurenai.png', NULL, 'Especialista em genjutsu.', 'Especialista em genjutsu. Ilusões confundem e controlam. Técnica mas frágil.', 'Tecnica', 'medium', '{"strength":5,"speed":6,"technique":9,"defense":5,"mobility":6,"versatility":7}'::jsonb, ARRAY['Tecnicas fortes','Kit versatil','Velocidade acima da media']::text[], ARRAY['Dano base menor','Defesa vulneravel']::text[], ARRAY['Kiba Inuzuka','Shino Aburame','Hinata Hyuuga']::text[], ARRAY['Itachi Uchiha','Sasuke Uchiha','Kakashi Hatake']::text[], 'Todos os jogadores', true, false, 37),
('tenten', 'Tenten', 'C', '/characters/tenten-pts.png', NULL, 'Especialista em armas.', 'Especialista em armas. Muitos projéteis mas dano baixo. Zoning fraco comparado a outros.', 'Tecnica', 'easy', '{"strength":6,"speed":6,"technique":7,"defense":5,"mobility":6,"versatility":6}'::jsonb, ARRAY['Tecnicas fortes','Dano alto','Velocidade acima da media']::text[], ARRAY['Defesa vulneravel','Dano base menor']::text[], ARRAY['Konohamaru','Hanabi Hyuuga']::text[], ARRAY['Gaara','Temari','Rock Lee']::text[], 'Todos os jogadores', true, false, 38),
('tenten-shippuden', 'Tenten Shippūden', 'C+', '/characters/tenten-ts.png', NULL, 'Tenten com mais arsenal.', 'Tenten com mais arsenal. Armas melhoradas mas ainda tier baixo. Mais opções de zoning.', 'Tecnica', 'easy', '{"strength":7,"speed":7,"technique":8,"defense":6,"mobility":6,"versatility":7}'::jsonb, ARRAY['Tecnicas fortes','Dano alto','Velocidade acima da media']::text[], ARRAY['Defesa vulneravel','Mobilidade limitada']::text[], ARRAY['Konohamaru','Hanabi Hyuuga','Ino Yamanaka']::text[], ARRAY['Gaara Shippūden','Temari Shippūden','Rock Lee Shippūden']::text[], 'Todos os jogadores', true, false, 39),
('kankurou', 'Kankurou', 'B', '/characters/kankuro-pts.png', NULL, 'Marionetista com Crow.', 'Marionetista com Crow. Controle à distância único. Curva de aprendizado alta.', 'Tecnica', 'medium', '{"strength":6,"speed":5,"technique":8,"defense":6,"mobility":5,"versatility":8}'::jsonb, ARRAY['Tecnicas fortes','Kit versatil','Dano alto']::text[], ARRAY['Velocidade menor','Mobilidade limitada']::text[], ARRAY['Ino Yamanaka','Shino Aburame','Tenten']::text[], ARRAY['Sasori','Rock Lee','Naruto Uzumaki']::text[], 'Todos os jogadores', true, false, 40),
('kankurou-shippuden', 'Kankurou Shippūden', 'B+', '/characters/kankuro-ts.png', NULL, 'Kankurou com múltiplas marionetes.', 'Kankurou com múltiplas marionetes. Sasori''s puppets adicionam versatilidade. Melhor controle.', 'Tecnica', 'medium', '{"strength":7,"speed":6,"technique":9,"defense":7,"mobility":6,"versatility":9}'::jsonb, ARRAY['Tecnicas fortes','Kit versatil','Dano alto']::text[], ARRAY['Velocidade menor','Mobilidade limitada']::text[], ARRAY['Ino Yamanaka Shippūden','Shino Aburame Shippūden','Tenten Shippūden']::text[], ARRAY['Sasori','Rock Lee Shippūden','Naruto Shippūden']::text[], 'Todos os jogadores', true, false, 41),
('temari', 'Temari', 'B+', '/characters/temari-pts.png', NULL, 'Controladora de vento com leque gigante.', 'Controladora de vento com leque gigante. Zoning de longo alcance. Anti-air forte.', 'Tecnica', 'medium', '{"strength":6,"speed":6,"technique":8,"defense":6,"mobility":6,"versatility":7}'::jsonb, ARRAY['Tecnicas fortes','Kit versatil','Dano alto']::text[], ARRAY['Dano base menor','Velocidade menor']::text[], ARRAY['Rock Lee','Kiba Inuzuka','Tenten']::text[], ARRAY['Shikamaru Nara','Gaara','Naruto Uzumaki']::text[], 'Todos os jogadores', true, false, 42),
('temari-shippuden', 'Temari Shippūden', 'A', '/characters/temari-ts.png', NULL, 'Temari mais poderosa.', 'Temari mais poderosa. Ventos mais fortes e controle de área melhorado. Zoning top tier.', 'Tecnica', 'hard', '{"strength":7,"speed":7,"technique":9,"defense":7,"mobility":7,"versatility":8}'::jsonb, ARRAY['Tecnicas fortes','Kit versatil','Dano alto']::text[], ARRAY['Dano base menor','Velocidade menor']::text[], ARRAY['Rock Lee Shippūden','Kiba Inuzuka Shippūden','Tenten Shippūden']::text[], ARRAY['Shikamaru Nara Shippūden','Gaara Shippūden','Naruto Shippūden']::text[], 'Todos os jogadores', true, false, 43),
('vovo-chiyo', 'Vovó Chiyo', 'B+', '/characters/reia.png', NULL, 'Anciã marionetista lendária.', 'Anciã marionetista lendária. Kit técnico com marionetes e antídotos. Requer paciência.', 'Tecnica', 'medium', '{"strength":5,"speed":5,"technique":9,"defense":6,"mobility":5,"versatility":8}'::jsonb, ARRAY['Tecnicas fortes','Kit versatil','Boa defesa']::text[], ARRAY['Dano base menor','Velocidade menor']::text[], ARRAY['Sasori','Kankurou','Ino Yamanaka']::text[], ARRAY['Rock Lee','Naruto Shippūden','Sasuke Shippūden']::text[], 'Todos os jogadores', true, false, 44),
('vovo-chiyo-taijutsu', 'Vovó Chiyo Taijutsu', 'B', '/characters/reia.png', NULL, 'Chiyo focada em combate corpo-a-corpo.', 'Chiyo focada em combate corpo-a-corpo. Menos marionetes, mais socos envenenados.', 'Tecnica', 'medium', '{"strength":6,"speed":6,"technique":7,"defense":6,"mobility":6,"versatility":6}'::jsonb, ARRAY['Tecnicas fortes','Dano alto','Velocidade acima da media']::text[], ARRAY['Dano base menor','Velocidade menor']::text[], ARRAY['Ino Yamanaka','Shino Aburame','Tenten']::text[], ARRAY['Rock Lee','Kiba Inuzuka','Naruto Uzumaki']::text[], 'Todos os jogadores', true, false, 45),
('vovo-chiyo-mestre-das-marionetes', 'Vovó Chiyo Mestre das Marionetes', 'A', '/characters/reia-marionete.png', NULL, 'Chiyo no auge do controle de marionetes.', 'Chiyo no auge do controle de marionetes. Arsenal completo com 10 marionetes.', 'Tecnica', 'hard', '{"strength":5,"speed":5,"technique":10,"defense":7,"mobility":5,"versatility":10}'::jsonb, ARRAY['Tecnicas fortes','Kit versatil','Boa defesa']::text[], ARRAY['Dano base menor','Velocidade menor']::text[], ARRAY['Sasori','Kankurou Shippūden','Deidara']::text[], ARRAY['Rock Lee Shippūden','Naruto Shippūden','Sasuke Shippūden']::text[], 'Todos os jogadores', true, false, 46),
('kisame-hoshigaki', 'Kisame Hoshigaki', 'A', '/characters/kisame.png', NULL, 'O Monstro da Névoa.', 'O Monstro da Névoa. Samehada drena chakra e força bruta massiva. Tank agressivo.', 'Pressao e dano', 'hard', '{"strength":9,"speed":6,"technique":7,"defense":8,"mobility":6,"versatility":7}'::jsonb, ARRAY['Dano alto','Boa defesa','Tecnicas fortes']::text[], ARRAY['Velocidade menor','Mobilidade limitada']::text[], ARRAY['Rock Lee','Might Guy','Asuma Sarutobi']::text[], ARRAY['Itachi Uchiha','Minato Namikaze','Naruto Shippūden']::text[], 'Todos os jogadores', true, false, 47),
('deidara', 'Deidara', 'A', '/characters/deidara.png', NULL, 'Artista explosivo com argila.', 'Artista explosivo com argila. Zoning extremo e mobilidade aérea. Glass cannon técnico.', 'Tecnica', 'hard', '{"strength":7,"speed":7,"technique":9,"defense":5,"mobility":8,"versatility":8}'::jsonb, ARRAY['Tecnicas fortes','Mobilidade forte','Kit versatil']::text[], ARRAY['Defesa vulneravel','Dano base menor']::text[], ARRAY['Gaara','Kankurou','Vovó Chiyo']::text[], ARRAY['Sasuke Shippūden','Itachi Uchiha','Kakashi Hatake']::text[], 'Todos os jogadores', true, false, 48),
('sasori', 'Sasori', 'A', '/characters/sasori.png', '/characters/sasori-lv2.png', 'Marionetista supremo.', 'Marionetista supremo. 100 marionetes e corpo próprio de madeira. Controle de área extremo.', 'Tecnica', 'hard', '{"strength":6,"speed":6,"technique":10,"defense":7,"mobility":5,"versatility":9}'::jsonb, ARRAY['Tecnicas fortes','Kit versatil','Boa defesa']::text[], ARRAY['Mobilidade limitada','Dano base menor']::text[], ARRAY['Kankurou','Shino Aburame','Ino Yamanaka']::text[], ARRAY['Vovó Chiyo Mestre das Marionetes','Sakura Haruno Shippūden','Naruto Shippūden']::text[], 'Todos os jogadores', true, false, 49),
('hiruko', 'Hiruko', 'B', '/characters/sasori-hiruku.png', NULL, 'Armadura marionete de Sasori.', 'Armadura marionete de Sasori. Tanky mas lento. Caudas venenosas para controle.', 'Defesa', 'medium', '{"strength":7,"speed":4,"technique":8,"defense":9,"mobility":4,"versatility":6}'::jsonb, ARRAY['Boa defesa','Tecnicas fortes','Dano alto']::text[], ARRAY['Velocidade menor','Mobilidade limitada']::text[], ARRAY['Tenten','Ino Yamanaka','Konohamaru']::text[], ARRAY['Sakura Haruno Shippūden','Rock Lee','Naruto Uzumaki']::text[], 'Todos os jogadores', true, false, 50),
('terceiro-kazekage', 'Terceiro Kazekage', 'A', '/characters/sasori.png', NULL, 'Marionete do Kazekage mais forte.', 'Marionete do Kazekage mais forte. Iron Sand devastador. Controle magnético supremo.', 'Tecnica', 'hard', '{"strength":8,"speed":6,"technique":10,"defense":7,"mobility":6,"versatility":9}'::jsonb, ARRAY['Tecnicas fortes','Kit versatil','Dano alto']::text[], ARRAY['Velocidade menor','Mobilidade limitada']::text[], ARRAY['Tenten','Kankurou','Temari']::text[], ARRAY['Gaara Shippūden','Sakura Haruno Shippūden','Naruto Shippūden']::text[], 'Todos os jogadores', true, false, 51),
('sai', 'Sai', 'B+', '/characters/sai.png', NULL, 'Artista ninja da ROOT.', 'Artista ninja da ROOT. Desenhos ganham vida para ataques. Kit único de zoning.', 'Tecnica', 'medium', '{"strength":6,"speed":7,"technique":8,"defense":5,"mobility":8,"versatility":8}'::jsonb, ARRAY['Tecnicas fortes','Mobilidade forte','Kit versatil']::text[], ARRAY['Defesa vulneravel','Dano base menor']::text[], ARRAY['Ino Yamanaka','Tenten','Kankurou']::text[], ARRAY['Sasuke Shippūden','Naruto Shippūden','Rock Lee']::text[], 'Todos os jogadores', true, false, 52),
('yamato', 'Yamato', 'A', '/characters/yamato.png', NULL, 'Wood Release artificial.', 'Wood Release artificial. Controle de área com madeira. Versátil e defensivo.', 'Tecnica', 'hard', '{"strength":7,"speed":6,"technique":9,"defense":8,"mobility":6,"versatility":9}'::jsonb, ARRAY['Tecnicas fortes','Kit versatil','Boa defesa']::text[], ARRAY['Velocidade menor','Mobilidade limitada']::text[], ARRAY['Naruto Uzumaki','Sai','Deidara']::text[], ARRAY['Hashirama Senju','Itachi Uchiha','Sasuke Shippūden']::text[], 'Todos os jogadores', true, false, 53),
('shizune', 'Shizune', 'C+', '/characters/shizune.png', NULL, 'Assistente médica com venenos.', 'Assistente médica com venenos. Suporte com debuffs. Fraca mas útil em matchups específicos.', 'Tecnica', 'easy', '{"strength":4,"speed":6,"technique":8,"defense":5,"mobility":6,"versatility":7}'::jsonb, ARRAY['Tecnicas fortes','Kit versatil','Velocidade acima da media']::text[], ARRAY['Dano base menor','Defesa vulneravel']::text[], ARRAY['Ino Yamanaka','Konohamaru','Hanabi Hyuuga']::text[], ARRAY['Tsunade','Sakura Haruno Shippūden','Rock Lee']::text[], 'Todos os jogadores', true, false, 54),
('kabuto-yakushi', 'Kabuto Yakushi', 'A', '/characters/kabuto.png', NULL, 'Ninja médico traidor.', 'Ninja médico traidor. Chakra Scalpel e regeneração. Kit técnico de counter-play.', 'Tecnica', 'hard', '{"strength":6,"speed":7,"technique":9,"defense":6,"mobility":7,"versatility":9}'::jsonb, ARRAY['Tecnicas fortes','Kit versatil','Velocidade acima da media']::text[], ARRAY['Dano base menor','Defesa vulneravel']::text[], ARRAY['Naruto Uzumaki','Shino Aburame','Kiba Inuzuka']::text[], ARRAY['Tsunade','Jiraiya','Orochimaru']::text[], 'Todos os jogadores', true, false, 55),
('jiroubou', 'Jiroubou', 'C', '/characters/girobo.png', '/characters/girobo-lv2.png', 'Tank do Sound Four.', 'Tank do Sound Four. Força bruta mas muito lento. Curse Mark aumenta poder.', 'Pressao e dano', 'easy', '{"strength":9,"speed":3,"technique":4,"defense":9,"mobility":3,"versatility":4}'::jsonb, ARRAY['Dano alto','Boa defesa','Tecnicas fortes']::text[], ARRAY['Velocidade menor','Mobilidade limitada']::text[], ARRAY['Ino Yamanaka','Tenten','Konohamaru']::text[], ARRAY['Chouji Akimichi','Rock Lee','Naruto Uzumaki']::text[], 'Todos os jogadores', true, false, 56),
('kidoumaru', 'Kidoumaru', 'B', '/characters/kidomaru.png', '/characters/kidomaru-lv2.png', 'Arqueiro aranha do Sound Four.', 'Arqueiro aranha do Sound Four. Zoning com teias e flechas. Kit de controle.', 'Tecnica', 'medium', '{"strength":6,"speed":6,"technique":8,"defense":5,"mobility":7,"versatility":8}'::jsonb, ARRAY['Tecnicas fortes','Kit versatil','Mobilidade forte']::text[], ARRAY['Defesa vulneravel','Dano base menor']::text[], ARRAY['Tenten','Ino Yamanaka','Shino Aburame']::text[], ARRAY['Neji Hyuuga','Rock Lee','Naruto Uzumaki']::text[], 'Todos os jogadores', true, false, 57),
('sakon-e-ukon', 'Sakon e Ukon', 'B+', '/characters/sakon.png', '/characters/sakon-lv2.png', 'Gêmeos fundidos.', 'Gêmeos fundidos. Ataques coordenados e fusão corporal. Kit único de pressão.', 'Pressao e dano', 'medium', '{"strength":7,"speed":7,"technique":7,"defense":6,"mobility":7,"versatility":7}'::jsonb, ARRAY['Dano alto','Velocidade acima da media','Tecnicas fortes']::text[], ARRAY['Defesa vulneravel','Dano base menor']::text[], ARRAY['Shino Aburame','Ino Yamanaka','Hinata Hyuuga']::text[], ARRAY['Kiba Inuzuka','Rock Lee','Naruto Uzumaki']::text[], 'Todos os jogadores', true, false, 58),
('tayuya', 'Tayuya', 'B', '/characters/tayuya.png', '/characters/tayuya-lv2.png', 'Flautista do Sound Four.', 'Flautista do Sound Four. Genjutsu sonoro e invocações. Controle mental único.', 'Tecnica', 'medium', '{"strength":5,"speed":6,"technique":9,"defense":5,"mobility":6,"versatility":8}'::jsonb, ARRAY['Tecnicas fortes','Kit versatil','Velocidade acima da media']::text[], ARRAY['Dano base menor','Defesa vulneravel']::text[], ARRAY['Ino Yamanaka','Shino Aburame','Hinata Hyuuga']::text[], ARRAY['Shikamaru Nara','Rock Lee','Temari']::text[], 'Todos os jogadores', true, false, 59),
('kimimaro', 'Kimimaro', 'A', '/characters/kimimaru.png', '/characters/kimimaru-lv2.png', 'Último do clã Kaguya.', 'Último do clã Kaguya. Manipulação óssea devastadora. Rushdown com defesa integrada.', 'Pressao e dano', 'hard', '{"strength":8,"speed":8,"technique":8,"defense":7,"mobility":8,"versatility":7}'::jsonb, ARRAY['Dano alto','Velocidade acima da media','Tecnicas fortes']::text[], ARRAY['Defesa vulneravel','Menos opcoes situacionais']::text[], ARRAY['Rock Lee','Naruto Uzumaki','Gaara']::text[], ARRAY['Gaara Shippūden','Tsunade','Itachi Uchiha']::text[], 'Todos os jogadores', true, false, 60),
('hanabi-hyuuga', 'Hanabi Hyuuga', 'C', '/characters/hanabi.png', NULL, 'Jovem Hyuuga.', 'Jovem Hyuuga. Gentle Fist básico mas promissor. Versão mais fraca de Hinata.', 'Velocidade', 'easy', '{"strength":5,"speed":7,"technique":7,"defense":5,"mobility":7,"versatility":5}'::jsonb, ARRAY['Velocidade acima da media','Tecnicas fortes','Mobilidade forte']::text[], ARRAY['Dano base menor','Defesa vulneravel']::text[], ARRAY['Konohamaru','Tenten']::text[], ARRAY['Hinata Hyuuga','Neji Hyuuga','Rock Lee']::text[], 'Todos os jogadores', true, false, 61),
('konohamaru', 'Konohamaru', 'C', '/characters/time-kohonomaru.png', NULL, 'Neto do Terceiro Hokage.', 'Neto do Terceiro Hokage. Kit básico com Rasengan em desenvolvimento. Low tier mas divertido.', 'Velocidade', 'easy', '{"strength":4,"speed":6,"technique":5,"defense":4,"mobility":6,"versatility":5}'::jsonb, ARRAY['Velocidade acima da media','Mobilidade forte','Tecnicas fortes']::text[], ARRAY['Dano base menor','Defesa vulneravel']::text[], ARRAY[]::text[], ARRAY['Naruto Uzumaki','Hanabi Hyuuga','Rock Lee']::text[], 'Todos os jogadores', true, false, 62),
('anko-mitarashi', 'Anko Mitarashi', 'B', '/characters/anko.png', NULL, 'Ex-aluna de Orochimaru.', 'Ex-aluna de Orochimaru. Invocação de cobras e jutsus proibidos. Kit agressivo com setups.', 'Tecnica', 'medium', '{"strength":6,"speed":7,"technique":8,"defense":5,"mobility":7,"versatility":7}'::jsonb, ARRAY['Tecnicas fortes','Velocidade acima da media','Mobilidade forte']::text[], ARRAY['Defesa vulneravel','Dano base menor']::text[], ARRAY['Ino Yamanaka','Tenten','Shino Aburame']::text[], ARRAY['Orochimaru','Jiraiya','Itachi Uchiha']::text[], 'Todos os jogadores', true, false, 63),
('haku', 'Haku', 'B+', '/characters/haku.png', NULL, 'Kekkei Genkai do gelo.', 'Kekkei Genkai do gelo. Crystal Ice Mirrors para mobilidade extrema. Glass cannon rápido.', 'Velocidade', 'medium', '{"strength":5,"speed":9,"technique":9,"defense":4,"mobility":9,"versatility":7}'::jsonb, ARRAY['Velocidade acima da media','Tecnicas fortes','Mobilidade forte']::text[], ARRAY['Defesa vulneravel','Dano base menor']::text[], ARRAY['Rock Lee','Kiba Inuzuka','Tenten']::text[], ARRAY['Sasuke Uchiha','Naruto Uzumaki','Kakashi Hatake']::text[], 'Todos os jogadores', true, false, 64),
('zabuza-momochi', 'Zabuza Momochi', 'A', '/characters/zabuza.png', NULL, 'Demônio da Névoa Oculta.', 'Demônio da Névoa Oculta. Kubikiribōchō devastadora e Silent Killing. Rushdown pesado.', 'Pressao e dano', 'hard', '{"strength":9,"speed":7,"technique":7,"defense":7,"mobility":6,"versatility":6}'::jsonb, ARRAY['Dano alto','Velocidade acima da media','Tecnicas fortes']::text[], ARRAY['Mobilidade limitada','Menos opcoes situacionais']::text[], ARRAY['Rock Lee','Tenten','Konohamaru']::text[], ARRAY['Kakashi Hatake','Naruto Uzumaki','Sasuke Uchiha']::text[], 'Todos os jogadores', true, false, 65)
ON CONFLICT (slug) DO UPDATE SET
  name = EXCLUDED.name,
  tier = EXCLUDED.tier,
  image_url = EXCLUDED.image_url,
  image_lv2_url = EXCLUDED.image_lv2_url,
  short_description = EXCLUDED.short_description,
  full_description = EXCLUDED.full_description,
  playstyle = EXCLUDED.playstyle,
  difficulty = EXCLUDED.difficulty,
  attributes = EXCLUDED.attributes,
  strengths = EXCLUDED.strengths,
  weaknesses = EXCLUDED.weaknesses,
  favorable_against = EXCLUDED.favorable_against,
  unfavorable_against = EXCLUDED.unfavorable_against,
  recommended_for = EXCLUDED.recommended_for,
  is_published = EXCLUDED.is_published,
  is_featured = EXCLUDED.is_featured,
  sort_order = EXCLUDED.sort_order;

INSERT INTO public.academy_character_moves (
  character_id, name, move_type, video_url, description, difficulty, sort_order
)
VALUES
((SELECT id FROM public.academy_characters WHERE slug = 'naruto-uzumaki'), 'Rasengan', 'special', NULL, 'Golpe especial de médio alcance com ótimo dano. Startup moderado mas seguro em block. Excelente para finalizar combos ou punir dashes.', 'expert', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'naruto-uzumaki'), 'Kage Bunshin', 'setup', NULL, 'Cria clones para mixup e pressure. Versátil para high/low e esquerda/direita. Gasta chakra mas abre muitas possibilidades.', 'expert', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'naruto-uzumaki'), 'Uzumaki Barrage', 'combo', NULL, 'Combo aéreo devastador usando clones. Excelente dano e corner carry.', 'expert', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'naruto-shippuden'), 'Rasen Shuriken', 'ultimate', NULL, 'Ultimate devastador de longo alcance. Requer setup mas causa dano massivo. Melhor usado após knockdown.', 'expert', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'naruto-shippuden'), 'Modo Sennin', 'buff', NULL, 'Aumenta todos os atributos temporariamente. Permite combos estendidos e dano adicional.', 'expert', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'naruto-shippuden'), 'Oodama Rasengan', 'special', NULL, 'Rasengan gigante com mais dano e range. Ótimo para punishes pesados.', 'expert', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'sasuke-uchiha'), 'Chidori', 'special', NULL, 'Rush elétrico devastador. Alto risco, alto retorno. Punishável em miss mas garantido em vários setups.', 'expert', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'sasuke-uchiha'), 'Sharingan Counter', 'counter', NULL, 'Counter de precisão que vira o jogo. Timing perfeito necessário.', 'expert', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'sasuke-uchiha'), 'Fireball Jutsu', 'projectile', NULL, 'Projétil clássico para controle de espaço. Bom em neutral.', 'expert', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'sasuke-shippuden'), 'Kirin', 'ultimate', NULL, 'Relâmpago massivo do céu. Lento mas imbloquável. Setup específico necessário.', 'expert', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'sasuke-shippuden'), 'Chidori Nagashi', 'defensive', NULL, 'Chidori em área. Ótimo para escapar de pressão e reset neutral.', 'expert', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'sasuke-shippuden'), 'Susanoo', 'transformation', NULL, 'Armadura temporária com ataques poderosos. Gasta chakra mas domina rounds.', 'expert', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'itachi-uchiha'), 'Tsukuyomi', 'command_grab', NULL, 'Genjutsu que paralisa. Funciona como command grab. Quebra turtle.', 'expert', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'itachi-uchiha'), 'Amaterasu', 'projectile', NULL, 'Chamas negras imbloquáveis. Lento mas constante chip damage.', 'expert', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'itachi-uchiha'), 'Susanoo', 'defensive', NULL, 'Armadura massiva. Absorve hits e permite counters.', 'expert', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'minato-namikaze'), 'Hiraishin', 'special', NULL, 'Teleporte instantâneo para kunai marcada. Mixup e escape supremos.', 'expert', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'minato-namikaze'), 'Rasengan', 'special', NULL, 'Rasengan original. Rápido, seguro e versátil.', 'expert', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'minato-namikaze'), 'Flying Thunder God Slash', 'ultimate', NULL, 'Combo devastador usando teleporte. Difícil de reagir.', 'expert', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'kakashi-hatake'), 'Raikiri', 'special', NULL, 'Versão aprimorada do Chidori. Mais rápido e seguro.', 'hard', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'kakashi-hatake'), 'Kamui', 'special', NULL, 'Teleporte dimensional. Esquiva projéteis e cria mixup.', 'hard', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'kakashi-hatake'), 'Sharingan Copy', 'versatile', NULL, 'Usa o último jutsu do oponente. Alta skill cap.', 'hard', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'jiraiya'), 'Rasengan', 'special', NULL, 'Rasengan versátil para combos e punishes.', 'hard', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'jiraiya'), 'Toad Oil Bullet', 'projectile', NULL, 'Projétil que desacelera oponente. Ótimo para setup.', 'hard', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'jiraiya'), 'Sage Mode', 'buff', NULL, 'Aumenta poder drasticamente. Permite combos devastadores.', 'hard', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'tsunade'), 'Cherry Blossom Impact', 'special', NULL, 'Soco que quebra guarda e causa stun. Ótimo para abrir defesas.', 'hard', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'tsunade'), 'Healing Jutsu', 'buff', NULL, 'Recupera vida gradualmente. Permite jogar mais agressivo.', 'hard', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'tsunade'), 'Mitotic Regeneration', 'transformation', NULL, 'Cura massiva e boost de stats. Vira partidas.', 'hard', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'orochimaru'), 'Kusanagi', 'special', NULL, 'Espada extensível com range massivo. Controla espaço.', 'hard', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'orochimaru'), 'Snake Hands', 'command_grab', NULL, 'Grab de longo alcance. Pega oponentes desprevenidos.', 'hard', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'orochimaru'), 'Edo Tensei', 'setup', NULL, 'Invoca aliados temporários. Pressão constante.', 'hard', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'hashirama-senju'), 'Wood Dragon', 'ultimate', NULL, 'Dragão de madeira massivo. Dano e controle extremos.', 'expert', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'hashirama-senju'), 'Deep Forest Emergence', 'setup', NULL, 'Cria floresta no stage. Limita movimento e cria vantagem.', 'expert', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'hashirama-senju'), 'Wood Clone', 'setup', NULL, 'Clones duráveis para pressão e mixup.', 'expert', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'tobirama-senju'), 'Water Dragon', 'special', NULL, 'Dragão de água poderoso. Bom dano e knockback.', 'hard', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'tobirama-senju'), 'Flying Thunder God', 'special', NULL, 'Teleporte que inventou. Rápido e versátil.', 'hard', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'tobirama-senju'), 'Tandem Paper Bombs', 'setup', NULL, 'Armadilhas explosivas. Controle de área.', 'hard', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'hiruzen-sarutobi'), 'Enma Staff', 'special', NULL, 'Bastão transformado. Range e dano sólidos.', 'hard', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'hiruzen-sarutobi'), 'Fire Dragon', 'projectile', NULL, 'Projétil de fogo massivo. Excelente zoning.', 'hard', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'hiruzen-sarutobi'), 'Reaper Death Seal', 'ultimate', NULL, 'Selo suicida. Alto risco, mata garantido.', 'hard', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'rock-lee'), 'Primary Lotus', 'special', NULL, 'Combo aéreo devastador. Requer setup mas dano garantido.', 'hard', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'rock-lee'), 'Leaf Hurricane', 'combo', NULL, 'Série de chutes rápidos. Excelente pressão.', 'hard', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'rock-lee'), 'Eight Gates', 'buff', NULL, 'Power-up temporário massivo. Drena vida mas poder extremo.', 'hard', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'rock-lee-modo-punho-zonzo'), 'Drunken Fist', 'stance', NULL, 'Stance imprevisível. Movimento errático confunde.', 'hard', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'rock-lee-modo-punho-zonzo'), 'Staggering Strike', 'special', NULL, 'Golpe cambaleante. Hitbox estranho dificulta defesa.', 'hard', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'rock-lee-modo-punho-zonzo'), 'Bottle Smash', 'special', NULL, 'Ataque com garrafa. Startup enganoso.', 'hard', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'rock-lee-shippuden'), 'Hidden Lotus', 'ultimate', NULL, 'Lotus oculta. Devastador mas requer setup.', 'hard', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'rock-lee-shippuden'), 'Dynamic Entry', 'special', NULL, 'Entrada explosiva. Ótimo gap closer.', 'hard', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'rock-lee-shippuden'), 'Konoha Whirlwind', 'combo', NULL, 'Combo de chutes versátil. Bom em neutral.', 'hard', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'neji-hyuuga'), '64 Palms', 'special', NULL, 'Série de golpes que fecha tenketsu. Alto dano e drena chakra.', 'hard', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'neji-hyuuga'), 'Rotation', 'defensive', NULL, 'Defesa giratória. Reflete projéteis e afasta rushdown.', 'hard', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'neji-hyuuga'), 'Air Palm', 'projectile', NULL, 'Projétil de ar. Bom para zoning.', 'hard', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'neji-hyuuga-shippuden'), '128 Palms', 'special', NULL, 'Versão estendida do 64 Palms. Mais dano e reach.', 'hard', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'neji-hyuuga-shippuden'), 'Eight Trigrams Vacuum Palm', 'projectile', NULL, 'Projétil de alcance maior. Melhor zoning.', 'hard', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'neji-hyuuga-shippuden'), 'Gentle Fist Art', 'combo', NULL, 'Combo preciso. Maximiza dano de tenketsu.', 'hard', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'gaara'), 'Sand Shield', 'auto_guard', NULL, 'Bloqueio automático. Protege de certos ataques.', 'hard', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'gaara'), 'Sand Coffin', 'command_grab', NULL, 'Grab à distância. Lento mas devastador.', 'hard', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'gaara'), 'Shukaku Transformation', 'transformation', NULL, 'Forma bijuu. Aumenta poder massivamente.', 'hard', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'gaara-shippuden'), 'Sand Tsunami', 'ultimate', NULL, 'Onda massiva de areia. Controle de área devastador.', 'hard', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'gaara-shippuden'), 'Third Eye', 'setup', NULL, 'Olho de areia para visão. Ajuda em reads.', 'hard', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'gaara-shippuden'), 'Desert Layered Imperial Funeral', 'special', NULL, 'Ataque de área. Excelente dano.', 'hard', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'might-guy'), 'Morning Peacock', 'special', NULL, 'Socos em chamas. Dano massivo em área.', 'hard', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'might-guy'), 'Noon Tiger', 'ultimate', NULL, 'Tigre de ar comprimido. Devastador.', 'hard', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'might-guy'), 'Dynamic Entry', 'special', NULL, 'Entrada explosiva clássica. Gap closer.', 'hard', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'sakura-haruno'), 'Cherry Blossom Clash', 'special', NULL, 'Soco carregado. Bom dano se conectar.', 'medium', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'sakura-haruno'), 'Inner Sakura', 'buff', NULL, 'Boost temporário de força.', 'medium', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'sakura-haruno'), 'Kunai Throw', 'projectile', NULL, 'Projétil básico. Ferramenta de neutral.', 'medium', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'sakura-haruno-shippuden'), 'Heaven Kick of Pain', 'special', NULL, 'Chute devastador do alto. Ótimo anti-air.', 'hard', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'sakura-haruno-shippuden'), 'Medical Ninjutsu', 'buff', NULL, 'Cura que permite trades favoráveis.', 'hard', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'sakura-haruno-shippuden'), 'Ground Shatter', 'special', NULL, 'Soco no chão. Área de efeito.', 'hard', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'shikamaru-nara'), 'Shadow Possession', 'command_grab', NULL, 'Paralisa oponente. Setup para combos.', 'medium', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'shikamaru-nara'), 'Shadow Strangle', 'special', NULL, 'Estrangula com sombra. Dano gradual.', 'medium', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'shikamaru-nara'), 'Shadow Sewing', 'setup', NULL, 'Múltiplas sombras. Controle de área.', 'medium', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'shikamaru-nara-shippuden'), 'Shadow Imitation Shuriken', 'projectile', NULL, 'Projétil que conecta sombras. Zoning.', 'hard', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'shikamaru-nara-shippuden'), 'Shadow Gathering', 'setup', NULL, 'Prepara múltiplas sombras. Setup poderoso.', 'hard', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'shikamaru-nara-shippuden'), 'Shadow–Neck Binding', 'ultimate', NULL, 'Estrangulamento garantido. Alto dano.', 'hard', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'chouji-akimichi'), 'Human Boulder', 'special', NULL, 'Rola como bola. Armadura e dano.', 'medium', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'chouji-akimichi'), 'Expansion Jutsu', 'buff', NULL, 'Aumenta tamanho. Mais dano e alcance.', 'medium', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'chouji-akimichi'), 'Partial Expansion', 'special', NULL, 'Expande partes. Ataques de longo alcance.', 'medium', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'chouji-akimichi-shippuden'), 'Butterfly Bullet Bombing', 'ultimate', NULL, 'Soco devastador em Butterfly Mode.', 'medium', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'chouji-akimichi-shippuden'), 'Super Expansion', 'transformation', NULL, 'Forma gigante. Controle de área.', 'medium', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'chouji-akimichi-shippuden'), 'Meat Tank', 'special', NULL, 'Boulder aprimorado. Mais rápido e forte.', 'medium', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'ino-yamanaka'), 'Mind Transfer', 'command_grab', NULL, 'Controla oponente. Alto risco, alto retorno.', 'easy', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'ino-yamanaka'), 'Mind Destruction', 'special', NULL, 'Confunde oponente. Inverte controles.', 'easy', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'ino-yamanaka'), 'Flower Ninja Art', 'setup', NULL, 'Pétalas que distraem.', 'easy', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'ino-yamanaka-shippuden'), 'Mind Transfer Clone', 'special', NULL, 'Transfer mais seguro usando clone.', 'medium', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'ino-yamanaka-shippuden'), 'Medical Ninjutsu', 'buff', NULL, 'Cura básica. Sustain em lutas longas.', 'medium', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'ino-yamanaka-shippuden'), 'Sensory Perception', 'setup', NULL, 'Detecta movimento. Ajuda em reads.', 'medium', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'asuma-sarutobi'), 'Flying Swallow', 'special', NULL, 'Lâminas de chakra. Bom dano e range.', 'medium', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'asuma-sarutobi'), 'Fire Style: Ash Pile Burning', 'projectile', NULL, 'Projétil de cinzas. Controle de área.', 'medium', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'asuma-sarutobi'), 'Wind Release', 'buff', NULL, 'Aumenta dano das lâminas.', 'medium', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'shino-aburame'), 'Parasitic Insects', 'setup', NULL, 'Libera insetos. Drenam chakra do oponente.', 'medium', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'shino-aburame'), 'Bug Clone', 'special', NULL, 'Clone de insetos. Bait e mixup.', 'medium', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'shino-aburame'), 'Insect Swarm', 'projectile', NULL, 'Enxame direcionado. Zoning.', 'medium', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'shino-aburame-shippuden'), 'Nano-Sized Venomous Insects', 'special', NULL, 'Insetos venenosos. Dano over time.', 'medium', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'shino-aburame-shippuden'), 'Insect Jar Technique', 'setup', NULL, 'Cria zona de insetos. Área de perigo.', 'medium', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'shino-aburame-shippuden'), 'Secret Technique: Insect Sphere', 'ultimate', NULL, 'Esfera de insetos. Alto dano.', 'medium', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'kiba-inuzuka'), 'Fang Over Fang', 'special', NULL, 'Ataque giratório com Akamaru. Multi-hit.', 'medium', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'kiba-inuzuka'), 'Man Beast Clone', 'buff', NULL, 'Akamaru vira clone. Dobra ataques.', 'medium', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'kiba-inuzuka'), 'Tunneling Fang', 'special', NULL, 'Rotação solo. Gap closer rápido.', 'medium', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'kiba-inuzuka-shippuden'), 'Wolf Fang Over Fang', 'special', NULL, 'Versão mais forte do Fang Over Fang.', 'medium', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'kiba-inuzuka-shippuden'), 'Three-Headed Wolf', 'transformation', NULL, 'Forma combinada. Poder massivo.', 'medium', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'kiba-inuzuka-shippuden'), 'Tail Chasing Fang Fang Rotating Fang', 'ultimate', NULL, 'Combo devastador com Akamaru.', 'medium', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'hinata-hyuuga'), 'Gentle Fist', 'combo', NULL, 'Série de golpes em tenketsu. Drena chakra.', 'medium', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'hinata-hyuuga'), 'Protection of the Eight Trigrams', 'defensive', NULL, 'Versão defensiva da Rotation.', 'medium', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'hinata-hyuuga'), 'Twin Lion Fists', 'special', NULL, 'Chakra em forma de leões. Alto dano.', 'medium', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'hinata-hyuuga-shippuden'), 'Eight Trigrams Sixty-Four Palms', 'special', NULL, '64 Palms aprendida. Alto dano.', 'medium', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'hinata-hyuuga-shippuden'), 'Gentle Step Twin Lion Fists', 'ultimate', NULL, 'Ultimate devastador. Requer setup.', 'medium', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'hinata-hyuuga-shippuden'), 'Byakugan', 'buff', NULL, 'Ativa visão 360°. Melhora defense.', 'medium', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'kurenai-yuuhi'), 'Demonic Illusion: Tree Binding Death', 'command_grab', NULL, 'Prende em árvore ilusória. Setup para combo.', 'medium', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'kurenai-yuuhi'), 'Genjutsu: Flower Petal Escape', 'defensive', NULL, 'Escapa em pétalas. Invulnerabilidade momentânea.', 'medium', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'kurenai-yuuhi'), 'Vine Bind', 'setup', NULL, 'Videiras que prendem. Zoning.', 'medium', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'tenten'), 'Rising Twin Dragons', 'ultimate', NULL, 'Chuva de armas. Muitos hits.', 'easy', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'tenten'), 'Weapon Scroll', 'projectile', NULL, 'Lança várias armas. Zoning básico.', 'easy', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'tenten'), 'Ninja Tool Barrage', 'special', NULL, 'Série de armas arremessadas.', 'easy', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'tenten-shippuden'), 'Bashōsen', 'special', NULL, 'Leque lendário com elementos. Versátil.', 'easy', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'tenten-shippuden'), 'Tensasai', 'ultimate', NULL, 'Chuva de armas aprimorada. Mais dano.', 'easy', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'tenten-shippuden'), 'Chain Binding', 'setup', NULL, 'Correntes que prendem. Setup.', 'easy', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'kankurou'), 'Crow', 'setup', NULL, 'Controla marionete Crow. Ataques à distância.', 'medium', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'kankurou'), 'Black Secret Technique', 'special', NULL, 'Combo com marionete. Alto dano.', 'medium', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'kankurou'), 'Poison Smoke Bomb', 'projectile', NULL, 'Bomba venenosa. Controle de área.', 'medium', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'kankurou-shippuden'), 'Scorpion', 'setup', NULL, 'Marionete Sasori. Ataques venenosos.', 'medium', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'kankurou-shippuden'), 'Black Ant', 'special', NULL, 'Marionete de captura. Command grab.', 'medium', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'kankurou-shippuden'), 'Salamander', 'ultimate', NULL, 'Marionete defensiva. Shield e counter.', 'medium', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'temari'), 'Wind Scythe Jutsu', 'projectile', NULL, 'Rajada de vento. Excelente zoning.', 'medium', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'temari'), 'Great Sickle Weasel Technique', 'special', NULL, 'Versão mais forte. Knockback.', 'medium', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'temari'), 'Summoning: Kamatari', 'ultimate', NULL, 'Invoca doninha de vento. Devastador.', 'medium', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'temari-shippuden'), 'Wind Release: Cast Net', 'setup', NULL, 'Rede de vento. Prende oponentes.', 'hard', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'temari-shippuden'), 'Dust Wind Technique', 'projectile', NULL, 'Vento com areia. Mais dano.', 'hard', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'temari-shippuden'), 'Great Task of the Dragon', 'ultimate', NULL, 'Tornado massivo. Controle de área.', 'hard', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'vovo-chiyo'), 'White Secret Technique', 'setup', NULL, 'Marionetes para controle.', 'medium', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'vovo-chiyo'), 'Chikamatsu Collection', 'special', NULL, 'Múltiplas marionetes. Pressão.', 'medium', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'vovo-chiyo'), 'One''s Own Life Reincarnation', 'ultimate', NULL, 'Revive aliado com chakra próprio.', 'medium', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'vovo-chiyo-taijutsu'), 'Poison Fist', 'special', NULL, 'Socos envenenados. DOT.', 'medium', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'vovo-chiyo-taijutsu'), 'Antidote', 'buff', NULL, 'Remove debuffs. Sustain.', 'medium', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'vovo-chiyo-taijutsu'), 'Lion Closing Roar', 'command_grab', NULL, 'Grab seguido de veneno.', 'medium', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'vovo-chiyo-mestre-das-marionetes'), 'Ten Puppets of Chikamatsu', 'ultimate', NULL, '10 marionetes lendárias. Devastador.', 'hard', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'vovo-chiyo-mestre-das-marionetes'), 'Mother and Father', 'special', NULL, 'Marionetes parentais. Combos.', 'hard', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'vovo-chiyo-mestre-das-marionetes'), 'Puppet Transfer', 'setup', NULL, 'Controla marionete inimiga temporariamente.', 'hard', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'kisame-hoshigaki'), 'Samehada Slash', 'special', NULL, 'Corte que drena chakra. Sustain.', 'hard', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'kisame-hoshigaki'), 'Water Prison', 'command_grab', NULL, 'Prisão de água. Imobiliza.', 'hard', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'kisame-hoshigaki'), 'Great Shark Bullet', 'ultimate', NULL, 'Tubarão de água massivo. Alto dano.', 'hard', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'deidara'), 'C1', 'projectile', NULL, 'Explosivos básicos. Spam de zoning.', 'hard', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'deidara'), 'C2 Dragon', 'setup', NULL, 'Dragão de argila. Plataforma e ataques.', 'hard', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'deidara'), 'C4 Karura', 'ultimate', NULL, 'Nano-explosivos. Dano massivo em área.', 'hard', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'sasori'), 'Iron Sand', 'special', NULL, 'Areia de ferro magnética. Controle.', 'hard', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'sasori'), 'Hundred Puppets', 'ultimate', NULL, '100 marionetes. Pressão absurda.', 'hard', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'sasori'), 'Core Transfer', 'defensive', NULL, 'Transfere núcleo. Sobrevive dano fatal.', 'hard', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'hiruko'), 'Poison Tail', 'special', NULL, 'Cauda venenosa. Range e DOT.', 'medium', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'hiruko'), 'Hidden Weapon', 'projectile', NULL, 'Armas escondidas. Surpresa.', 'medium', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'hiruko'), 'Shell Defense', 'defensive', NULL, 'Carapaça protetora. Tanking.', 'medium', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'terceiro-kazekage'), 'Iron Sand World Method', 'ultimate', NULL, 'Espinhos de ferro em todas direções.', 'hard', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'terceiro-kazekage'), 'Iron Sand Drizzle', 'projectile', NULL, 'Chuva de ferro. Zoning.', 'hard', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'terceiro-kazekage'), 'Magnetic Control', 'setup', NULL, 'Controla armas metálicas inimigas.', 'hard', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'sai'), 'Super Beast Imitating Drawing', 'setup', NULL, 'Cria bestas de tinta. Pressão.', 'medium', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'sai'), 'Ink Bird', 'special', NULL, 'Pássaro para mobilidade aérea.', 'medium', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'sai'), 'Sealing Technique', 'command_grab', NULL, 'Sela oponente temporariamente.', 'medium', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'yamato'), 'Wood Release: Great Forest', 'setup', NULL, 'Floresta de madeira. Controle de área.', 'hard', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'yamato'), 'Wood Clone', 'special', NULL, 'Clone durável. Bait e mixup.', 'hard', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'yamato'), 'Wood Prison', 'command_grab', NULL, 'Prisão de madeira. Imobiliza.', 'hard', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'shizune'), 'Poison Needle', 'projectile', NULL, 'Agulhas venenosas. DOT.', 'easy', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'shizune'), 'Medical Ninjutsu', 'buff', NULL, 'Cura básica. Sustain.', 'easy', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'shizune'), 'Ninja Art: Poison Fog', 'setup', NULL, 'Névoa venenosa. Área de dano.', 'easy', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'kabuto-yakushi'), 'Chakra Scalpel', 'special', NULL, 'Corta tendões. Desabilita temporariamente.', 'hard', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'kabuto-yakushi'), 'Dead Soul Technique', 'setup', NULL, 'Controla corpo morto. Distração.', 'hard', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'kabuto-yakushi'), 'Healing Technique', 'buff', NULL, 'Regeneração. Sustain forte.', 'hard', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'jiroubou'), 'Earth Dome Prison', 'setup', NULL, 'Domo que drena chakra.', 'easy', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'jiroubou'), 'Rising Stone', 'special', NULL, 'Pilares de pedra. Anti-air.', 'easy', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'jiroubou'), 'Curse Mark Level 2', 'transformation', NULL, 'Forma amaldiçoada. Boost massivo.', 'easy', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'kidoumaru'), 'Spider Web', 'setup', NULL, 'Teias que prendem. Zoning.', 'medium', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'kidoumaru'), 'Spider War Bow', 'projectile', NULL, 'Flecha precisa. Alto dano.', 'medium', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'kidoumaru'), 'Curse Mark Level 2', 'transformation', NULL, 'Forma amaldiçoada. Mais braços.', 'medium', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'sakon-e-ukon'), 'Parasite Demon', 'command_grab', NULL, 'Funde com oponente. Dano gradual.', 'medium', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'sakon-e-ukon'), 'Multiple Connected Fists', 'combo', NULL, 'Socos coordenados. Multi-hit.', 'medium', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'sakon-e-ukon'), 'Curse Mark Level 2', 'transformation', NULL, 'Forma amaldiçoada. Separação.', 'medium', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'tayuya'), 'Demonic Flute', 'setup', NULL, 'Melodia que controla. Genjutsu.', 'medium', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'tayuya'), 'Doki Summoning', 'special', NULL, 'Invoca demônios. Pressão.', 'medium', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'tayuya'), 'Curse Mark Level 2', 'transformation', NULL, 'Forma amaldiçoada. Melodias mais fortes.', 'medium', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'kimimaro'), 'Digital Shrapnel', 'projectile', NULL, 'Ossos como projéteis. Zoning.', 'hard', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'kimimaro'), 'Dance of the Camellia', 'special', NULL, 'Espada óssea. Combos elegantes.', 'hard', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'kimimaro'), 'Bracken Dance', 'ultimate', NULL, 'Campo de ossos. Controle de área.', 'hard', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'hanabi-hyuuga'), 'Gentle Fist', 'combo', NULL, 'Combo básico em tenketsu.', 'easy', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'hanabi-hyuuga'), 'Byakugan', 'buff', NULL, 'Ativa visão. Melhora reação.', 'easy', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'hanabi-hyuuga'), 'Palm Strike', 'special', NULL, 'Golpe de palma. Knockback.', 'easy', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'konohamaru'), 'Sexy Jutsu', 'special', NULL, 'Distração. Abre para ataque.', 'easy', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'konohamaru'), 'Rasengan (Weak)', 'special', NULL, 'Rasengan fraco mas funcional.', 'easy', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'konohamaru'), 'Shadow Clone', 'setup', NULL, 'Clones básicos. Mixup simples.', 'easy', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'anko-mitarashi'), 'Twin Snakes', 'special', NULL, 'Cobra dupla. Ataque surpresa.', 'medium', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'anko-mitarashi'), 'Hidden Shadow Snake', 'command_grab', NULL, 'Grab com cobra. Rápido.', 'medium', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'anko-mitarashi'), 'Cursed Seal Pain', 'buff', NULL, 'Ativa selo. Boost temporário.', 'medium', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'haku'), 'Crystal Ice Mirrors', 'setup', NULL, 'Espelhos para teleporte. Mobilidade.', 'medium', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'haku'), 'Thousand Needles of Death', 'projectile', NULL, 'Senbon de gelo. Multi-hit.', 'medium', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'haku'), 'Ice Prison', 'command_grab', NULL, 'Prisão de gelo. Imobiliza.', 'medium', 3),
((SELECT id FROM public.academy_characters WHERE slug = 'zabuza-momochi'), 'Silent Killing', 'special', NULL, 'Ataque na névoa. Invisível.', 'hard', 1),
((SELECT id FROM public.academy_characters WHERE slug = 'zabuza-momochi'), 'Hidden Mist', 'setup', NULL, 'Cria névoa. Esconde movimentos.', 'hard', 2),
((SELECT id FROM public.academy_characters WHERE slug = 'zabuza-momochi'), 'Water Dragon', 'ultimate', NULL, 'Dragão de água. Alto dano.', 'hard', 3)
ON CONFLICT (character_id, name, move_type) DO UPDATE SET
  video_url = EXCLUDED.video_url,
  description = EXCLUDED.description,
  difficulty = EXCLUDED.difficulty,
  sort_order = EXCLUDED.sort_order;
