// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dzrgcyhovmomyoztzmoq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR6cmdjeWhvdm1vbXlvenR6bW9xIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcxNDgyMjgsImV4cCI6MjA2MjcyNDIyOH0.yVkjJmyuEGDoGgT8pZ_L_rvs2Z6TbMofrwcY5ZRxUxc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});